# Generated by Django 6.0.1 on 2026-01-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING_DELETE', 'PENDING_DELETE'), ('PENDING_REPLACE', 'PENDING_REPLACE'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='ACTIVE', max_length=20),
        ),
    ]
