# Generated by Django 6.0.1 on 2026-01-18 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='request_type',
            field=models.CharField(choices=[('DELETE', 'DELETE'), ('REPLACE', 'REPLACE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_DELETE', 'PENDING_DELETE'), ('PENDING_REPLACE', 'PENDING_REPLACE'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20),
        ),
    ]
