# Generated by Django 6.0.1 on 2026-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permissionrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_DELETE', 'Pending Delete'), ('PENDING_REPLACE', 'Pending Replace'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
